### ISSUE TITLE
Bullseye - Modul says just "loading"

### ISSUE THREAD

**Issue by Softyathome** [jclarke0000/MMM-MyWastePickup#15]
Hi,

i didn't get any data from MMM-MyWastePickup.
Running MM 2.18 under Bullseye on a Raspberry 3b

Node and npm version:
pi@MM3:~ $ node -v
v16.13.2
pi@MM3:~ $ npm -v
8.1.2

The content (test entries) of my schedule_custom.csv:
Calendar,WeekStarting,GreenBin,Garbage,Recycling,YardWaste,ChristmasTree
Custom,02/07/22,0,1,0,0,0
Custom,02/08/22,0,0,1,0,0
Custom,03/02/22,0,1,0,0,0
Custom,03/09/22,0,1,0,0,0
Custom,03/10/22,1,0,0,0,0

My config regarding 
                {
                        module: "MMM-MyWastePickup",
                        position: "top_center",
  //                    header: "M&uuml;llabfuhr",
                        header: "WASTE",
                        config: {
                                collectionCalendar: "Custom",
                                weeksToDisplay: "2"
                        }
                },

PM2 log:
pi@MM3:~/MagicMirror $ pm2 log
[TAILING] Tailing last 15 lines for [all] processes (change the value with --lines option)
/home/pi/.pm2/pm2.log last 15 lines:
PM2        | 2022-02-06T22:00:22: PM2 log: PM2 version          : 5.1.2
PM2        | 2022-02-06T22:00:22: PM2 log: Node.js version      : 17.4.0
PM2        | 2022-02-06T22:00:22: PM2 log: Current arch         : arm
PM2        | 2022-02-06T22:00:22: PM2 log: PM2 home             : /home/pi/.pm2
PM2        | 2022-02-06T22:00:22: PM2 log: PM2 PID file         : /home/pi/.pm2/pm2.pid
PM2        | 2022-02-06T22:00:22: PM2 log: RPC socket file      : /home/pi/.pm2/rpc.sock
PM2        | 2022-02-06T22:00:22: PM2 log: BUS socket file      : /home/pi/.pm2/pub.sock
PM2        | 2022-02-06T22:00:22: PM2 log: Application log path : /home/pi/.pm2/logs
PM2        | 2022-02-06T22:00:22: PM2 log: Worker Interval      : 30000
PM2        | 2022-02-06T22:00:22: PM2 log: Process dump file    : /home/pi/.pm2/dump.pm2
PM2        | 2022-02-06T22:00:22: PM2 log: Concurrent actions   : 2
PM2        | 2022-02-06T22:00:22: PM2 log: SIGTERM timeout      : 1600
PM2        | 2022-02-06T22:00:22: PM2 log: ===============================================================================
PM2        | 2022-02-06T22:00:22: PM2 log: App [mm:0] starting in -fork mode-
PM2        | 2022-02-06T22:00:22: PM2 log: App [mm:0] online

/home/pi/.pm2/logs/MagicMirror-error.log last 15 lines:
0|mm       |     at /home/pi/MagicMirror/modules/MMM-MyWastePickup/node_helper.js:36:9
0|mm       |     at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3)
0|mm       | [06.02.2022 21:37.41.484] [ERROR] MagicMirror will not quit, but it might be a good idea to check why this happened. Maybe no internet connection?
0|mm       | [06.02.2022 21:37.41.485] [ERROR] If you think this really is an issue, please open an issue on GitHub: https://github.com/MichMich/MagicMirror/issues
0|mm       | [1468:0100/000000.525475:ERROR:connection.cc(66)] X connection error received.
0|mm       | [07.02.2022 06:05.42.345] [WARN]  The module 'weatherforecast' is deprecated in favor of the 'weather'-module, please refer to the documentation for a migration path
0|mm       | [1440:0207/060546.132881:ERROR:viz_main_impl.cc(161)] Exiting GPU process due to errors during initialization
0|mm       | [1483:0207/060547.287531:ERROR:viz_main_impl.cc(161)] Exiting GPU process due to errors during initialization
0|mm       | [1502:0207/060550.327609:ERROR:sandbox_linux.cc(376)] InitializeSandbox() called with multiple threads in process gpu-process.
0|mm       | [07.02.2022 06:05.57.254] [ERROR] Whoops! There was an uncaught exception...
0|mm       | [07.02.2022 06:05.57.264] [ERROR] TypeError: parse is not a function
0|mm       |     at /home/pi/MagicMirror/modules/MMM-MyWastePickup/node_helper.js:36:9
0|mm       |     at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3)
0|mm       | [07.02.2022 06:05.57.266] [ERROR] MagicMirror will not quit, but it might be a good idea to check why this happened. Maybe no internet connection?
0|mm       | [07.02.2022 06:05.57.267] [ERROR] If you think this really is an issue, please open an issue on GitHub: https://github.com/MichMich/MagicMirror/issues

/home/pi/.pm2/logs/MagicMirror-out.log last 15 lines:
0|mm       | [07.02.2022 06:05.42.349] [LOG]   Starting node helper for: newsfeed
0|mm       | [07.02.2022 06:05.42.350] [LOG]   Sockets connected & modules started ...
0|mm       | [07.02.2022 06:05.43.840] [LOG]   Launching application.
0|mm       | [07.02.2022 06:05.56.764] [LOG]   Create new newsfetcher for url: https://rss.nytimes.com/services/xml/rss/nyt/HomePage.xml - Interval: 300000
0|mm       | [07.02.2022 06:05.56.895] [INFO]  Checking git for module: MMM-MyWastePickup
0|mm       | [07.02.2022 06:05.57.216] [INFO]  Checking git for module: MMM-Fuel
0|mm       | [07.02.2022 06:05.57.294] [INFO]  Checking git for module: MMM-OpenWeather24Hours
0|mm       | [07.02.2022 06:05.57.357] [INFO]  Checking git for module: default
0|mm       | [07.02.2022 06:05.58.648] [INFO]  Newsfeed-Fetcher: Broadcasting 61 items.
0|mm       | [07.02.2022 06:10.59.278] [INFO]  Newsfeed-Fetcher: Broadcasting 62 items.
0|mm       | [07.02.2022 06:15.59.864] [INFO]  Newsfeed-Fetcher: Broadcasting 62 items.
0|mm       | [07.02.2022 06:21.00.369] [INFO]  Newsfeed-Fetcher: Broadcasting 62 items.
0|mm       | [07.02.2022 06:26.00.875] [INFO]  Newsfeed-Fetcher: Broadcasting 62 items.

Maybe the reason can be found around this error:

`! There was an uncaught exception…
0|mm | [07.02.2022 06:05.57.264] [ERROR] TypeError: parse is not a function
0|mm | at /home/pi/MagicMirror/modules/MMM-MyWastePickup/node_helper.js:36:9`

BR
Jens

**Comment by maximilianbiebl** [comment]
Is there something new on how to fix the error?

**Comment by Softyathome** [comment]
Sorry, habe dich komplett vergessen …

Ich habe nun MMM-MyGarbage installiert

https://github.com/htilburgs/MMM-MyGarbage

 

Sorry, completely forgot about you ...

I have now installed MMM-MyGarbage

 

Gruß / Best regards

Jens

 

Von: maximilianbiebl ***@***.***> 
Gesendet: Dienstag, 5. Juli 2022 16:06
An: jclarke0000/MMM-MyWastePickup ***@***.***>
Cc: Softyathome ***@***.***>; Author ***@***.***>
Betreff: Re: [jclarke0000/MMM-MyWastePickup] Bullseye - Modul says just "loading" (Issue #15)

 

Is there something new on how to fix the error?
